// Deep_upskilling/Module2_FrontendDev/handson_05/student_project/src/components/CourseCard.jsx
function CourseCard({
    id,
    name,
    code,
    credits,
    grade,
    onEnroll
}) {
    return (
        <div className="course-card">
            <h3>{name}</h3>

            <p>Code: {code}</p>

            <p>Credits: {credits}</p>

            <p>Grade: {grade}</p>

            <button onClick={() => onEnroll(id)}>
                Enroll
            </button>
        </div>
    );
}

export default CourseCard;

// Deep_upskilling/Module2_FrontendDev/handson_08/student-portal-vue/src/components/CourseCard.vue
<template>
  <div class="course-card">

    <h3>{{ name }}</h3>

    <p>Code: {{ code }}</p>

    <p>Credits: {{ credits }}</p>

    <p>Grade: {{ grade }}</p>

  </div>
</template>

<script setup>

defineProps({
  name: String,
  code: String,
  credits: Number,
  grade: String
})

</script>

<style scoped>

.course-card {
  background: white;
  border-radius: 8px;
  padding: 15px;
  margin-bottom: 15px;

  box-shadow: 0 2px 5px rgba(0,0,0,0.1);
}

</style>
